apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uxlyumdzy-nodejs 
  janus-idp.io/tekton: uxlyumdzy-nodejs
  backstage.io/kubernetes-id: uxlyumdzy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uxlyumdzy-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  